[package]
name = "kando-cosmic-helper"
version = "0.1.0"
authors = ["Sam Ludford <samludford76@gmail.com>"]
repository = "https://github.com/sam-ludford/kando-cosmic-integration"
edition = "2021"
license = "MIT"
description = "D-Bus helper required for Kando on the COSMIC desktop"

[dependencies]
wayland-client = "0.31"
wayland-protocols = { version = "0.32", features = ["client", "staging", "unstable"] }
wayland-protocols-wlr = { version = "0.3", features = ["client"] }
wayland-protocols-misc = { version = "0.3", features = ["client"] }
cosmic-protocols = { version = "0.2", default-features = false, features = ["client"] }
xkbcommon = "0.9"
zbus = { version = "5", default-features = false, features = ["async-io", "blocking-api"] }
libc = "0.2"

[profile.release]
strip = true
lto = true
